//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServiceApp.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoServiceEntities : DbContext
    {
        public AutoServiceEntities()
            : base("name=AutoServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auto> Auto { get; set; }
        public virtual DbSet<AutoType> AutoType { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<MoreParts> MoreParts { get; set; }
        public virtual DbSet<NameMark> NameMark { get; set; }
        public virtual DbSet<NameModel> NameModel { get; set; }
        public virtual DbSet<Repair> Repair { get; set; }
        public virtual DbSet<RepairCategory> RepairCategory { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SparePart> SparePart { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
