//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServiceApp.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoreParts
    {
        public int IdMoreParts { get; set; }
        public Nullable<int> IdRepair { get; set; }
        public Nullable<int> IdSpareParts { get; set; }
    
        public virtual Repair Repair { get; set; }
        public virtual SparePart SparePart { get; set; }
    }
}
